CREATE DATABASE HomeLibaryMS
USE HomeLibaryMS
CREATE TABLE PUBLISHER (
	name VARCHAR(100) PRIMARY KEY NOT NULL,
	address VARCHAR(60) NOT NULL,
	phone VARCHAR(15) NOT NULL

);

CREATE TABLE BOOK (
	bookid INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	title VARCHAR(100) NOT NULL,
	publisherName VARCHAR(100) NOT NULL CONSTRAINT fk_publisherName FOREIGN KEY REFERENCES PUBLISHER(name) ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE BOOK_AUTHORS (
	bookid INT NOT NULL FOREIGN KEY REFERENCES BOOK(bookid) ON UPDATE CASCADE ON DELETE CASCADE,
	authorName VARCHAR(30) NOT NULL
);

CREATE TABLE BORROWER (
	cardNo INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	name VARCHAR(30) NOT NULL,
	address VARCHAR(60) NOT NULL,
	phone VARCHAR(15) NOT NULL
);

CREATE TABLE LIBRARY_BRANCH (
	branchid INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	branchName VARCHAR(50) NOT NULL,
	address VARCHAR(30) NOT NULL
);

CREATE TABLE BOOK_LOANS (
	bookid INT PRIMARY KEY NOT NULL CONSTRAINT fk_bookidloans FOREIGN KEY REFERENCES BOOK(bookid) ON UPDATE CASCADE ON DELETE CASCADE,
	branchid INT NOT NULL CONSTRAINT fk_branchidloans FOREIGN KEY REFERENCES LIBRARY_BRANCH(branchid) ON UPDATE CASCADE ON DELETE CASCADE,
	cardNo INT NOT NULL CONSTRAINT fk_CardNoloans FOREIGN KEY REFERENCES BORROWER(cardNo) ON UPDATE CASCADE ON DELETE CASCADE,
	dateOut DATE NOT NULL,
	dueDate DATE NOT NULL  
);

CREATE TABLE BOOK_COPIES (
	bookid INT PRIMARY KEY NOT NULL CONSTRAINT fk_bookidcopies FOREIGN KEY REFERENCES BOOK(bookid) ON UPDATE CASCADE ON DELETE CASCADE,
	branchid INT NOT NULL CONSTRAINT fk_branchidcopies FOREIGN KEY REFERENCES LIBRARY_BRANCH(branchid) ON UPDATE CASCADE ON DELETE CASCADE,
	no_of_copies INT NOT NULL
);

